name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        working-directory: GiftCardSite
        run: ./gradlew build